import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { Navbar } from "./components/Navbar";
import { SessionProvider } from "next-auth/react";
import { auth } from "~/server/auth";
import ToastContainer from "./components/ToastContainer";
import ToastProvider from "~/contexts/useToast";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  let session = null;
  try {
    session = await auth();
    console.log(session);
  } catch (error) {
    console.error("Error fetching session:", error);
  }

  if (session == null) return <div></div>;

  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <SessionProvider session={session}>
          <ToastProvider>
            <Navbar />
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </ToastProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
